services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    command: uvicorn app.api_rest:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy

  worker:
    build: .
    command: python -m app.worker
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      replicas: 2 # Sobem 2 workers por padrão para demonstrar divisão de carga

  grpc:
    build: .
    command: python -m app.servidor_grpc
    ports:
      - "50051:50051"
    environment:
      - REDIS_URL=redis://redis:6379/0
